CREATE TABLE accounts(
	id INT PRIMARY KEY AUTO_INCREMENT,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	birthDate DATE NOT NULL,
	signUpDate DATE NOT NULL,
	accountStatus VARCHAR(255) NOT NULL
);

CREATE TABLE users(
	id INT PRIMARY KEY AUTO_INCREMENT,
	login VARCHAR(255) NOT NULL UNIQUE,
	account_id INT NOT NULL UNIQUE,
	FOREIGN KEY(account_id) REFERENCES accounts(id)
);

CREATE TABLE files(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	userId INT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT NOW(),
	updated TIMESTAMP NULL DEFAULT NULL,
	status VARCHAR(255) NOT NULL,
	user_id INT,
	FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE events(
	id INT PRIMARY KEY AUTO_INCREMENT,
	fileId INT NOT NULL,
	fileName VARCHAR(255) NOT NULL,
	eventTime TIMESTAMP NOT NULL DEFAULT NOW(),
	action VARCHAR(255) NOT NULL,
	user_id INT,
	FOREIGN KEY(user_id) REFERENCES users(id)
);